language: csharp
mono: none
dotnet: 3.1.422
script:
- ./build.sh
- ./test.sh
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
  on:
    branch: master