language: csharp
mono: none
dotnet: 2.1.403
branches:
script:
- chmod +x ./build.sh && ./build.sh
- chmod +x ./test.sh && ./test.sh
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
  on:
    branch: master